name: python3_8
channels:
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - alsa-lib=1.2.6.1=h7f98852_0
  - aom=3.4.0=h27087fc_1
  - attr=2.5.1=h166bdaf_1
  - avalanche-lib=0.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - blas=1.0=mkl
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py38h0a891b7_1004
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2023.01.10=h06a4308_0
  - cairo=1.16.0=ha61ee94_1012
  - certifi=2022.12.7=py38h06a4308_0
  - cffi=1.15.1=py38h4a40e3a_0
  - click=8.1.3=py38h578d9bd_0
  - cloudpickle=2.1.0=pyhd8ed1ab_0
  - cryptography=37.0.4=py38h2b5fc30_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cython=0.29.32=py38hfa26641_0
  - dbus=1.13.6=h5008d03_3
  - decorator=5.1.0=pyhd3eb1b0_0
  - docker-pycreds=0.4.0=py_0
  - expat=2.4.8=h27087fc_0
  - ffmpeg=4.4.2=gpl_h45a1190_107
  - fftw=3.3.10=nompi_ha7695d1_103
  - filelock=3.8.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.36.0=py38h0a891b7_0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.11.0=h70c0345_0
  - gdown=4.5.1=pyhd8ed1ab_0
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h7b6447c_0
  - gitdb=4.0.9=pyhd8ed1ab_0
  - glib=2.72.1=h6239696_0
  - glib-tools=2.72.1=h6239696_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.7.7=hf3e180e_0
  - gputil=1.4.0=pyh9f0ad1d_0
  - graphite2=1.3.13=h58526e2_1001
  - grpc-cpp=1.48.0=hbad87ad_3
  - gst-plugins-base=1.20.3=hf6a322e_0
  - gstreamer=1.20.3=hd4edc92_0
  - gym=0.21.0=py38he5a9106_2
  - harfbuzz=5.1.0=hf9f4e7c_0
  - hdf5=1.12.2=nompi_h2386368_100
  - higher=0.2.1=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - importlib-metadata=4.11.4=py38h578d9bd_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipdb=0.13.9=pyhd8ed1ab_0
  - ipython=7.29.0=py38hb070fc8_0
  - jack=1.9.18=h8c3723f_1002
  - jasper=2.0.33=ha77e612_0
  - jedi=0.18.0=py38h06a4308_1
  - jpeg=9e=h166bdaf_2
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=4.0.0=h27087fc_0
  - libabseil=20220623.0=cxx17_h48a1fff_1
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcap=2.64=ha37c62d_0
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=14.0.6=default_h2e3cab8_0
  - libclang13=14.0.6=default_h3a83d3e_0
  - libcups=2.3.3=h3e49a29_2
  - libcurl=7.83.1=h7bff187_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.13=h166bdaf_0
  - libdrm=2.4.112=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libflac=1.3.4=h27087fc_0
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libglib=2.72.1=h2d90d5f_0
  - libglu=9.0.0=he1b5a44_1001
  - libiconv=1.16=h516909a_0
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm14=14.0.6=he0ac6c6_0
  - libnghttp2=1.47.0=hdcd2b5c_1
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopencv=4.6.0=py38h3504efa_3
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.16=h516909a_0
  - libpng=1.6.37=hbc83047_0
  - libpq=14.5=hd77ab85_0
  - libprotobuf=3.20.1=h6239696_1
  - libsndfile=1.0.31=h9c3ff4c_1
  - libsqlite=3.39.2=h753d276_1
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtasn1=4.18.0=h166bdaf_1
  - libtiff=4.4.0=h0e0dad5_3
  - libtool=2.4.6=h9c3ff4c_1008
  - libudev1=249=h166bdaf_4
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.40.0=h7b6447c_0
  - libva=2.15.0=h166bdaf_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.2.4=h522a892_0
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.14=h22db469_4
  - libzlib=1.2.12=h166bdaf_2
  - llvm-openmp=14.0.4=he0ac6c6_0
  - lz4-c=1.9.3=h295c915_1
  - markupsafe=2.1.1=py38h0a891b7_1
  - matplotlib-base=3.5.2=py38h826bfd8_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.30=haf5c9bc_0
  - mysql-libs=8.0.30=h28c427c_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.8.1=hc379101_1
  - nspr=4.32=h9c3ff4c_1
  - nss=3.78=h2350873_0
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.3.0=h27087fc_0
  - openssl=1.1.1t=h7f8727e_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=21.3=pyhd8ed1ab_0
  - parso=0.8.2=pyhd3eb1b0_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pixman=0.40.0=h36c2ea0_0
  - portaudio=19.6.0=h57a0ea0_5
  - promise=2.3=py38h578d9bd_6
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - psutil=5.9.1=py38h0a891b7_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pulseaudio=14.0=h7f54b18_8
  - py-opencv=4.6.0=py38h7f3c49e_3
  - pycocotools=2.0.4=py38h71d37f0_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py38h578d9bd_5
  - python=3.8.13=h582c2e5_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=1.10.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytorchcv=0.0.67=pyhd8ed1ab_0
  - pyyaml=6.0=py38h0a891b7_4
  - qt-main=5.15.4=ha5833f6_2
  - quadprog=0.1.11=py38h43d8883_1
  - re2=2022.06.01=h27087fc_0
  - readline=8.1.2=h0f457ee_0
  - sentry-sdk=1.9.5=pyhd8ed1ab_0
  - setproctitle=1.3.2=py38h0a891b7_0
  - setuptools=58.0.4=py38h06a4308_0
  - shortuuid=1.0.9=pyha770c72_1
  - six=1.16.0=pyhd3eb1b0_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.39.2=h4ff8645_1
  - svt-av1=1.2.0=h27087fc_0
  - tk=8.6.12=h27826a3_0
  - torchaudio=0.10.0=py38_cu113
  - torchmetrics=0.9.3=pyhd8ed1ab_0
  - torchvision=0.11.1=py38_cu113
  - tqdm=4.62.3=pyhd3eb1b0_1
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.3.0=hd8ed1ab_0
  - typing_extensions=4.3.0=pyha770c72_0
  - unicodedata2=14.0.0=py38h0a891b7_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.0=h166bdaf_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h166bdaf_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h166bdaf_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.8.1=pyhd8ed1ab_0
  - zlib=1.2.12=h166bdaf_2
  - zstd=1.5.2=h6239696_4
  - pip:
      - absl-py==0.14.1
      - accelerate==0.18.0
      - adapter-transformers==3.0.1
      - addict==2.4.0
      - aenum==3.1.12
      - aiofiles==23.1.0
      - aiohttp==3.8.1
      - aiosignal==1.2.0
      - albumentations==1.3.0
      - altair==5.0.1
      - aniso8601==9.0.1
      - antlr4-python3-runtime==4.9.3
      - anyio==3.7.0
      - anykeystore==0.2
      - apex==0.1
      - astroid==2.15.6
      - async-timeout==4.0.2
      - attrs==22.1.0
      - autofaiss==2.15.6
      - basicsr==1.4.2
      - blendmodes==2022
      - blinker==1.6.2
      - boltons==23.0.0
      - braceexpand==0.1.7
      - cachetools==4.2.4
      - chardet==4.0.0
      - charset-normalizer==2.0.12
      - clean-fid==0.1.29
      - clip-anytorch==2.5.2
      - clip-retrieval==2.37.0
      - colorama==0.4.5
      - commonmark==0.9.1
      - continuum==1.2.7
      - coolname==1.1.0
      - cryptacular==1.6.2
      - cycler==0.10.0
      - dataclasses==0.6
      - datasets==1.9.0
      - defusedxml==0.7.1
      - deprecation==2.1.0
      - dill==0.3.5.1
      - dodgy==0.2.1
      - easydict==1.10
      - einops==0.4.1
      - embedding-reader==1.5.0
      - entrypoints==0.3
      - exceptiongroup==1.1.1
      - exifread-nocycle==3.0.1
      - facexlib==0.3.0
      - faiss-cpu==1.7.4
      - fastapi==0.94.0
      - ffmpy==0.3.0
      - filterpy==1.4.5
      - fire==0.4.0
      - flake8==5.0.4
      - flake8-polyfill==1.0.2
      - flask==2.3.2
      - flask-cors==3.0.10
      - flask-restful==0.3.10
      - font-roboto==0.0.1
      - fonts==0.0.3
      - frozenlist==1.3.1
      - fsspec==2022.11.0
      - ftfy==6.1.1
      - future==0.18.3
      - gfpgan==1.3.8
      - gitpython==3.1.30
      - google-auth==2.20.0
      - google-auth-oauthlib==1.0.0
      - gradio==3.29.0
      - gradio-client==0.2.6
      - greenlet==1.1.2
      - grpcio==1.54.2
      - h11==0.12.0
      - h5py==3.8.0
      - httpcore==0.15.0
      - httpx==0.24.1
      - huggingface-hub==0.0.8
      - hupper==1.10.3
      - hydra-core==1.2.0
      - idna==2.10
      - imagehash==4.3.1
      - imageio==2.31.1
      - img2dataset==1.41.0
      - importlib-resources==5.9.0
      - inflection==0.5.1
      - iniconfig==1.1.1
      - isort==4.3.21
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - joblib==1.0.1
      - jsonlines==2.0.0
      - jsonmerge==1.8.0
      - jsonpatch==1.32
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - kiwisolver==1.3.2
      - kornia==0.6.7
      - lark==1.1.2
      - lazy-loader==0.2
      - lazy-object-proxy==1.9.0
      - lightning-utilities==0.8.0
      - linkify-it-py==2.0.2
      - littleutils==0.2.2
      - llvmlite==0.40.0
      - lmdb==1.4.1
      - lpips==0.1.4
      - markdown==3.3.4
      - markdown-it-py==2.2.0
      - matplotlib==3.4.3
      - mccabe==0.7.0
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - mmcls==0.23.1
      - mmcv-full==1.5.3
      - model-index==0.1.11
      - multidict==6.0.2
      - multilingual-clip==1.0.10
      - multiprocess==0.70.13
      - mypy==1.5.1
      - mypy-extensions==1.0.0
      - networkx==3.1
      - nltk==3.8.1
      - nose==1.3.7
      - numba==0.57.0
      - numpy==1.23.5
      - oauthlib==3.1.1
      - ogb==1.3.6
      - omegaconf==2.2.3
      - open-clip-torch==2.20.0
      - opencv-python==4.6.0.66
      - opencv-python-headless==4.7.0.72
      - openmim==0.2.0
      - ordered-set==4.1.0
      - orjson==3.9.1
      - outdated==0.2.2
      - pandas==1.5.3
      - pastedeploy==2.1.1
      - pathtools==0.1.2
      - pbkdf2==1.3
      - pep8-naming==0.10.0
      - piexif==1.1.3
      - pillow==9.4.0
      - pip==20.2.4
      - pkgutil-resolve-name==1.3.10
      - plaster==1.0
      - plaster-pastedeploy==0.7
      - platformdirs==3.10.0
      - pluggy==1.0.0
      - prettytable==3.3.0
      - progress==1.6
      - prometheus-client==0.17.0
      - prospector==1.10.2
      - protobuf==3.18.1
      - py==1.11.0
      - pyarrow==7.0.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycodestyle==2.9.1
      - pydantic==1.10.9
      - pydeprecate==0.3.2
      - pydocstyle==6.3.0
      - pydub==0.25.1
      - pyflakes==2.5.0
      - pygments==2.15.1
      - pylint==2.17.5
      - pylint-celery==0.3
      - pylint-django==2.5.3
      - pylint-flask==0.6
      - pylint-plugin-utils==0.7
      - pyparsing==2.4.7
      - pyramid==2.0
      - pyramid-mailer==0.15.1
      - pyrsistent==0.19.3
      - pytest==7.1.2
      - pytest-mock==3.11.1
      - python-dotenv==0.20.0
      - python-multipart==0.0.6
      - python3-openid==3.2.0
      - pytorch-lightning==1.9.4
      - pytorch-lightning-bolts==0.3.2.post1
      - pytorch-yard==2022.8.19.4
      - pytz==2021.3
      - pywavelets==1.4.1
      - pyzmq==23.2.0
      - qudida==0.0.4
      - realesrgan==0.3.0
      - regex==2023.5.5
      - repoze-sendmail==4.4.1
      - requests==2.25.1
      - requests-oauthlib==1.3.0
      - requirements-detector==1.2.2
      - resize-right==0.0.2
      - responses==0.18.0
      - rich==12.4.4
      - rsa==4.7.2
      - sacremoses==0.0.53
      - safetensors==0.3.1
      - scikit-image==0.19.2
      - scikit-learn==1.0
      - scipy==1.7.1
      - seaborn==0.11.2
      - semantic-version==2.10.0
      - semver==3.0.1
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - setoptconf-tmp==0.3.1
      - sklearn==0.0.post9
      - smmap==5.0.0
      - sniffio==1.3.0
      - snowballstemmer==2.2.0
      - spherecluster==0.1.7
      - sqlalchemy==1.4.39
      - starlette==0.26.1
      - tabulate==0.8.10
      - tb-nightly==2.14.0a20230615
      - tensorboard==2.6.0
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.0
      - tensorboardx==2.2
      - termcolor==2.3.0
      - threadpoolctl==3.0.0
      - tifffile==2023.4.12
      - timm==0.6.7
      - tokenizers==0.10.1
      - toml==0.10.2
      - tomli==2.0.1
      - tomlkit==0.12.1
      - toolz==0.12.0
      - torchdiffeq==0.2.3
      - torchfile==0.1.0
      - torchsde==0.2.5
      - torchstat==0.0.7
      - torchsummary==1.5.1
      - tornado==6.2
      - trampoline==0.1.2
      - transaction==3.0.1
      - transformers==4.4.2
      - translationstring==1.4
      - typer==0.6.1
      - tzdata==2023.3
      - uc-micro-py==1.0.2
      - urllib3==1.25.11
      - uvicorn==0.22.0
      - velruse==1.1.1
      - venusian==3.0.0
      - visdom==0.1.8.9
      - wandb==0.12.21
      - webdataset==0.2.48
      - webob==1.8.7
      - websocket-client==1.3.3
      - websockets==11.0.3
      - werkzeug==2.3.4
      - wheel==0.40.0
      - wild==1.0.4
      - wilds==1.2.2
      - wrapt==1.15.0
      - wtforms==3.0.1
      - wtforms-recaptcha==0.3.2
      - xxhash==3.2.0
      - yacs==0.1.8
      - yapf==0.32.0
      - yarl==1.8.1
      - zope-deprecation==4.4.0
      - zope-interface==5.4.0
      - zope-sqlalchemy==1.6
prefix: /home/liangys/anaconda3/envs/python3_8
